// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gamesApi.Data;

#nullable disable

namespace gamesApi.Migrations
{
    [DbContext(typeof(GamesContext))]
    [Migration("20260330201010_AddDealers")]
    partial class AddDealers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("gamesApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("gamesApi.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dealers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "вул. Хрещатик, 10",
                            Brand = "Toyota",
                            City = "Київ",
                            Name = "AutoHub Kyiv",
                            Phone = "+380441234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "вул. Стрийська, 45",
                            Brand = "BMW",
                            City = "Львів",
                            Name = "BMW Center Lviv",
                            Phone = "+380322345678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "вул. Дерибасівська, 22",
                            Brand = "Nissan",
                            City = "Одеса",
                            Name = "Nissan Motors Odesa",
                            Phone = "+380483456789"
                        },
                        new
                        {
                            Id = 4,
                            Address = "просп. Перемоги, 88",
                            Brand = "Honda",
                            City = "Київ",
                            Name = "Honda Plaza",
                            Phone = "+380444567890"
                        },
                        new
                        {
                            Id = 5,
                            Address = "вул. Європейська, 5",
                            Brand = "Mercedes",
                            City = "Дніпро",
                            Name = "Mercedes Premium",
                            Phone = "+380565678901"
                        },
                        new
                        {
                            Id = 6,
                            Address = "вул. Сумська, 30",
                            Brand = "Audi",
                            City = "Харків",
                            Name = "Audi Centre",
                            Phone = "+380576789012"
                        },
                        new
                        {
                            Id = 7,
                            Address = "бул. Лесі Українки, 12",
                            Brand = "Ford",
                            City = "Київ",
                            Name = "Ford Ukraine",
                            Phone = "+380447890123"
                        },
                        new
                        {
                            Id = 8,
                            Address = "вул. Городоцька, 100",
                            Brand = "Toyota",
                            City = "Львів",
                            Name = "Toyota West",
                            Phone = "+380328901234"
                        });
                });

            modelBuilder.Entity("gamesApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Config = "{\"items\":[],\"cardBack\":\"\",\"hints\":5,\"title\":\"Magic Memory\"}",
                            Description = "",
                            Genre = "Logic",
                            ImageUrl = "",
                            IsSystem = true,
                            Slug = "magicMemory"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
