// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gamesApi.Data;

#nullable disable

namespace gamesApi.Migrations
{
    [DbContext(typeof(GamesContext))]
    [Migration("20260329180349_AddCars")]
    partial class AddCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("gamesApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Color = "Red",
                            Model = "Supra",
                            Price = 55000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Toyota",
                            Color = "White",
                            Model = "Camry",
                            Price = 28000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            Color = "Black",
                            Model = "M3",
                            Price = 72000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BMW",
                            Color = "Blue",
                            Model = "X5",
                            Price = 65000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Nissan",
                            Color = "Silver",
                            Model = "GTR",
                            Price = 115000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Honda",
                            Color = "Red",
                            Model = "Civic",
                            Price = 24000m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Honda",
                            Color = "Black",
                            Model = "Accord",
                            Price = 32000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Mercedes",
                            Color = "White",
                            Model = "C63 AMG",
                            Price = 85000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Audi",
                            Color = "Gray",
                            Model = "RS6",
                            Price = 120000m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Ford",
                            Color = "Yellow",
                            Model = "Mustang",
                            Price = 45000m,
                            Year = 2021
                        });
                });

            modelBuilder.Entity("gamesApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Config = "{\"items\":[],\"cardBack\":\"\",\"hints\":5,\"title\":\"Magic Memory\"}",
                            Description = "",
                            Genre = "Logic",
                            ImageUrl = "",
                            IsSystem = true,
                            Slug = "magicMemory"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
